### ISSUE TITLE
Help with deploying

### ISSUE THREAD

**Issue by smamudhan** [MaxwellBo/Muncoordinated-2#43]
Hey, we're a school-MUN trying to deploy our own instance of MUNcoordinated for our MUN and we're having trouble after the initial firebase deploy - we downloaded the .zip and deployed to a firebase project (https://mc-pleasework.firebaseapp.com)

The page just shows up as blank, after several attempts. We love muncoordinated and we were hoping you might be able to help us get this working!

**Comment by MaxwellBo** [comment]
Hi! Is there any reason that you're not using the hosted version at muncoordinated.io ? Otherwise, if you've forked the project I can walk you through running your own copy over Facebook or something.

**Comment by smamudhan** [comment]
Hey, we're not using the hosted version as we need to hand this entire thing over to UNIC (United Nations Information Centre) after we're done - as part of our collaboration with them. We're depending on MUNcoordinated to help us with the data collection for the audit. I hope that's okay.

I'd be more than happy to connect with you and figure this out! We really need this to work.
We're also open to the idea of you helping us set it up for a small fee, if that's okay with you!

Please let me know

**Comment by MaxwellBo** [comment]
Sweet, ping me at max@maxbo.me and we can exchange some IM details on a platform of your choice.

**Comment by MaxwellBo** [comment]
Okay, I'm going to bed and I can help you tomorrow but here's the deal.

"Handing the entire thing over" might not be possible due to a hard dependency on Firebase - Muncoordinated will not run standalone. You have two options here.

    a) You use the hosted version of muncoordinated.io, and I add an option on the committee onboarding screen that effectively says "I agree to grant access to the United Nations Information Centre anonymised data for <REASON>. At the end, I get all the committees that have that flag enabled and I send you big fat `.json` of all that data.
   b) You don't do that, and instead you do the following.

1. Fork this repo
2. Create a new Heroku project.
3. Set it up to deploy from the new GitHub project with the [create-react-app buildpack](https://github.com/mars/create-react-app-buildpack)
4. Create a new Firebase project
5. Swap out the [firebaseConfig](https://github.com/MaxwellBo/Muncoordinated-2/blob/master/src/App.tsx#L15) with the one your Firebase project provides you.
6. Load the [database rules](https://github.com/MaxwellBo/Muncoordinated-2/blob/master/database.rules.json)

**Comment by MaxwellBo** [comment]
Okay, I'm going to bed and I can help you tomorrow but here's the deal.

"Handing the entire thing over" might not be possible due to a hard dependency on Firebase - Muncoordinated will not run standalone. You have two options here.

a) You use the hosted version of muncoordinated.io, and I add an option on the committee onboarding screen that effectively says "I agree to grant access to the United Nations Information Centre anonymised data for <REASON>. At the end, I get all the committees that have that flag enabled and I send you big fat `.json` of all that data. 
b) You don't do that, and go through the entire process of deploying this thing by hand.

**Comment by smamudhan** [comment]
Unfortunately, it would seem that option b is the right fit for us.
I have forked and deployed on Heroku - it seems to be working fine for now
- Can I let you know if we face issues down the road?

**Comment by MaxwellBo** [comment]
Before I can commit to support down the line, I'd like to discuss your usecase privately over IM.

**Comment by smamudhan** [comment]
Of course!
Here's my hangouts ID: sm.amudhan@simunglobal.org
Or please connect with me over skype: sm.amudhan

**Comment by MaxwellBo** [comment]
Pinged on Skype
